[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Configuración para las funciones serverless
[functions]
  node_bundler = "esbuild"

# Variables de entorno para producción
# Estas se configurarán en el panel de Netlify
# EMAIL_USER = "aristaenergia@gmail.com"
# EMAIL_PASS = "amvbgwirqynfesey"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!US"]}

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"